// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Fj5IvD0YO0CnR4Ygf1SNdnGd2TLzNGY',
    appId: '1:826464040168:web:8b9bac5cb419b29adb055d',
    messagingSenderId: '826464040168',
    projectId: 'offsecdairy-wsa',
    authDomain: 'offsecdairy-wsa.firebaseapp.com',
    storageBucket: 'offsecdairy-wsa.firebasestorage.app',
    measurementId: 'G-EGKYDLGNXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlMfSIJN2hNvtw0OTECFsOCwxonO-Kmg',
    appId: '1:826464040168:android:8f98387a42ff5cfbdb055d',
    messagingSenderId: '826464040168',
    projectId: 'offsecdairy-wsa',
    storageBucket: 'offsecdairy-wsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPH2EqnHw-XtslTuwrvj737WoeoUJy9lc',
    appId: '1:826464040168:ios:8d055f003cd1ae80db055d',
    messagingSenderId: '826464040168',
    projectId: 'offsecdairy-wsa',
    storageBucket: 'offsecdairy-wsa.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPH2EqnHw-XtslTuwrvj737WoeoUJy9lc',
    appId: '1:826464040168:ios:8d055f003cd1ae80db055d',
    messagingSenderId: '826464040168',
    projectId: 'offsecdairy-wsa',
    storageBucket: 'offsecdairy-wsa.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Fj5IvD0YO0CnR4Ygf1SNdnGd2TLzNGY',
    appId: '1:826464040168:web:4bf845d2a7114ed4db055d',
    messagingSenderId: '826464040168',
    projectId: 'offsecdairy-wsa',
    authDomain: 'offsecdairy-wsa.firebaseapp.com',
    storageBucket: 'offsecdairy-wsa.firebasestorage.app',
    measurementId: 'G-V73BKL0SVB',
  );
}
